global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'hashsphere-consensus'
    static_configs:
      - targets: ['hsphere-consensus:80']
        labels:
          role: 'consensus'

  - job_name: 'hashsphere-mirror'
    static_configs:
      - targets: ['hsphere-mirror:80']
        labels:
          role: 'mirror'
